# Generated by Django 5.2.1 on 2025-06-06 14:52

import django.core.validators
import django.db.models.deletion
import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amministratore_Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('codice_fiscale', models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(16)])),
                ('cellulare', models.CharField(max_length=20)),
                ('data_nascita', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('presenze_effettive', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Paziente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('codice_fiscale', models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(16)])),
                ('patologie', models.TextField(null=True)),
                ('allergie', models.TextField(null=True)),
                ('cellulare', models.CharField(max_length=20)),
                ('indirizzo', models.CharField(max_length=255)),
                ('data_nascita', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Personale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('ruolo', django_mysql.models.EnumField(choices=[('Medico', 'Medico'), ('Operatore Sanitario', 'Operatore Sanitario')], default='Medico')),
                ('codice_fiscale', models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(16)])),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('data_nascita', models.DateField()),
                ('orario_lavoro', models.CharField(max_length=100)),
                ('cellulare', models.CharField(max_length=20)),
                ('specializzazione', models.CharField(blank=True, max_length=100, null=True)),
                ('reparto', models.CharField(blank=True, max_length=100, null=True)),
                ('qualifica', models.CharField(blank=True, max_length=100, null=True)),
                ('mansione', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cartella_Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_apertura', models.DateField()),
                ('diagnosi', models.TextField()),
                ('prescrizioni', models.TextField(blank=True, null=True)),
                ('data_chiusura', models.DateField(blank=True, null=True)),
                ('paziente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Clinica.paziente')),
            ],
        ),
        migrations.CreateModel(
            name='Iscrizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_iscrizione', models.DateField(auto_now_add=True)),
                ('presente', models.BooleanField(default=False)),
                ('stato', models.CharField(choices=[('iscritto', 'Iscritto'), ('annullato', 'Annullato'), ('in_attesa', 'In attesa')], default='iscritto', max_length=50)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinica.evento')),
                ('paziente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clinica.paziente')),
                ('personale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clinica.personale')),
            ],
        ),
        migrations.CreateModel(
            name='Gestione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinica.cartella_clinica')),
                ('personale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinica.personale')),
            ],
        ),
        migrations.CreateModel(
            name='Trattamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', django_mysql.models.EnumField(choices=[('Ricovero', 'Ricovero'), ('Riabilitazione', 'Riabilitazione')], default='Ricovero')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('note', models.TextField(blank=True, null=True)),
                ('data_inizio', models.DateField(blank=True, null=True)),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('stanza', models.CharField(blank=True, max_length=10, null=True)),
                ('durata', models.IntegerField(blank=True, null=True)),
                ('gestore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clinica.amministratore_clinica')),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinica.paziente')),
            ],
        ),
        migrations.CreateModel(
            name='Svolgimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinica.personale')),
                ('trattamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinica.trattamento')),
            ],
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('valutazione', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinica.paziente')),
                ('trattamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinica.trattamento')),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                ('durata', models.PositiveIntegerField(default=30)),
                ('stato', models.CharField(choices=[('richiesta', 'Richiesta'), ('confermata', 'Confermata'), ('cancellata', 'Cancellata'), ('modificata', 'Modificata')], default='richiesta', max_length=30)),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinica.paziente')),
                ('personale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clinica.personale')),
                ('trattamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinica.trattamento')),
            ],
        ),
        migrations.AddField(
            model_name='cartella_clinica',
            name='trattamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clinica.trattamento'),
        ),
    ]
