# Generated by Django 5.2.1 on 2025-06-08 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0002_trattamento_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trattamento',
            name='paziente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clinica.paziente'),
        ),
    ]
