# Generated by Django 5.2.1 on 2025-06-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0003_alter_trattamento_paziente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iscrizione',
            name='stato',
            field=models.CharField(choices=[('iscritto', 'Iscritto'), ('annullato', 'Annullato')], default='iscritto', max_length=50),
        ),
    ]
