# Generated by Django 5.2.1 on 2025-06-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0004_alter_iscrizione_stato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='stato',
            field=models.CharField(choices=[('richiesta', 'Richiesta'), ('confermata', 'Confermata'), ('cancellata', 'Cancellata')], default='richiesta', max_length=30),
        ),
    ]
